# Generated by Django 5.0.1 on 2024-02-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature',
            new_name='Features',
        ),
    ]
