# Generated by Django 5.0.1 on 2024-02-16 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_feature1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature1',
        ),
    ]
