# Generated by Django 5.0.1 on 2024-02-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_feature1'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
